name: Build
on:
  push:
    branches:
      - 'main'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: kaisugi/action-regex-match@v1.0.0
        id: regex-match
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '^v[0-9]+\.[0-9]+\.[0-9]+$'

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Unit tests
        run: bash ./gradlew test

      - name: Build Changelog
        if: ${{ steps.regex-match.outputs.match != '' }}
        id: changelog
        uses: ardalanamini/auto-changelog@v3
        with:
          mention-authors: false
          mention-new-contributors: false
          include-compare: false
          semver: false

      - name: Create Release
        if: ${{ steps.regex-match.outputs.match != '' }}
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          tag: ${{ github.event.head_commit.message }}
          name: Release ${{ github.event.head_commit.message }}
          token: ${{ secrets.GITHUB_TOKEN }}