name: Test Build
on:
  push:
    branches:
      - '**'
jobs:
  Build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build APK
        run: bash ./gradlew assembleRelease

      - name: Build Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}